version: '3.8'

services:
  db:
    image: postgres:13
    container_name: postgres
    environment:
      POSTGRES_USER: fastapi_user
      POSTGRES_PASSWORD: fastapi_password
      POSTGRES_DB: fastapi_db
    volumes:
      - postgres_data:/var/lib/postgresql/data
    ports:
      - "5433:5432"

  fastapi:
    build: .
    container_name: fastapi
    environment:
      DATABASE_HOST: db
      DATABASE_PORT: 5432
      DATABASE_USER: fastapi_user
      DATABASE_PASSWORD: fastapi_password
      DATABASE_NAME: fastapi_db
    ports:
      - "8009:8009"
    depends_on:
      - db

volumes:
  postgres_data: